services:
  - type: web
    name: assistente-professor
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python flask_app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: true
