services:
  - type: web
    name: assistente-professor-ia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python generate_index.py && uvicorn main:app --host 0.0.0.0 --port $PORT
